package com.xrouter.compiler;

import com.squareup.javapoet.ClassName;

public class Constants {
    public static final String JAVA_DOC = " DO NOT EDIT THIS FILE!!! IT WAS GENERATED BY XROUTER. ";

    public static final String PACKAGE_OF_GENERATED_CODE = "com.xrouter.routes";

    public static final String ROUTE_GROUP_PREFIX = "XRouter_Group_";
    public static final ClassName ROUTE_GROUP_ClASS_NAME = ClassName.get("com.xrouter", "IRouteGroup");

    public static final ClassName ROUTE_ROOT_ClASS_NAME = ClassName.get("com.xrouter", "IRouteRoot");

    public static final ClassName ROUTE_META_CLASS_NAME = ClassName.get("com.xrouter", "RouteMeta");

}
